### ISSUE TITLE
When motion detected, it's triggered many times.

### ISSUE THREAD

**Issue by Zulex** [raspberrypilearning/parent-detector#12]
Hello all, 

i'm trying to set up the parent detector without the camera but only writing down the time. Everytime motion is detected I write the current time to the console using datetime. But when there is motion it prints it like 20 times from 1 motion. When using time.sleep(1) it reduces it to 4 times writing it to the console. When using time.sleep(5) I got 1 log to the console but it's not able to write it every 5 seconds, it does it every 15 or so. So my question is, how can I get a accurate motion detection without printing multiple logs for a movement that happend in 1 second. My current code looks like this : 

```
import datetime
from gpiozero import MotionSensor

pir = MotionSensor(4)
while True:
    if pir.motion_detected:
        print(datetime.datetime.now())
        print("Motion detected!")
        time.sleep(x) # high value for x = lower message per simple movement = 3*x time before it can detect new movement.
```

thanks!

**Comment by lawsie** [comment]
Hi Zulex, thanks for your question. A couple of thoughts:

1. Did you try adjusting the sensitivity of the PIR using the potentiometers, as described in the resource?

2. We often put the PIR sensor in a cup or something similar so that it does not generate too many readings in a short period of time.

3. The quality of the PIR sensor can also affect this - the cheap ones are not as good. 

I am not sure why your code would only log movement at 3x instead of x intervals though. That doesn't seem logical. I wonder if @MarcScott has any thoughts.

**Comment by lawsie** [comment]
I haven't heard anything from you in a while so I'm going to close this issue and assume it is resolved. If it isn't, feel free to open another :)
